ARG APPLICATION_JDK_VERSION
FROM openjdk:${APPLICATION_JDK_VERSION}-jre

RUN mkdir /application

WORKDIR /application

COPY target/demo-*.jar demo.jar

ARG APPLICATION_NAME
ARG APPLICATION_DESCRIPTION
ARG APPLICATION_VENDOR_NAME
ARG APPLICATION_VERSION
ARG APPLICATION_VERSION_HASH
ARG APPLICATION_VERSION_STRING
ARG APPLICATION_BUILD_DATE

ENV APPLICATION_NAME=${APPLICATION_NAME}
ENV APPLICATION_DESCRIPTION=${APPLICATION_DESCRIPTION}
ENV APPLICATION_VENDOR_NAME=${APPLICATION_VENDOR_NAME}
ENV APPLICATION_VERSION=${APPLICATION_VERSION}
ENV APPLICATION_VERSION_HASH=${APPLICATION_VERSION_HASH}
ENV APPLICATION_VERSION_STRING=${APPLICATION_VERSION_STRING}
ENV APPLICATION_BUILD_DATE=${APPLICATION_BUILD_DATE}

LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.name="${APPLICATION_NAME}"
LABEL org.label-schema.description="${APPLICATION_DESCRIPTION}"
LABEL org.label-schema.vendor="${APPLICATION_VENDOR_NAME}"
LABEL org.label-schema.version="${APPLICATION_VERSION}"
LABEL org.label-schema.build-date="${APPLICATION_BUILD_DATE}"

CMD ["java", "-jar", "demo.jar"]
